### ISSUE TITLE
Refactor and unify required odML attribute handling in format, parser and validation

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/python-odml#229]
Currently we are have conflicting information and usage regarding which odML attributes are required and how and where missing required attributes are handled.

- `format.py` contains maps via the `_args` attribute that generically specify whether an attribute of an odML entity is required or not. These specifications are unfortunately only sparsely used throughout the project.
- `format.py` currently defines only Section `type` and Property `name` as required.
- The constructors in `section.py` and `property.py` both require just `name`, but do not check for any other attributes that might be required as defined in `format.py`.
- The odML validation in `validation.py` does not contain checks for required attributes as defined via `format.py`.
- The XML parser contains a hard coded check for Section `name`.
- The Dict parser which handles the yaml and json formats contain no checks whatsoever.

A solution to resolve this issue would be to
- [x] define Section `name` and `type` as well as Property `name` as required in `format.py`.
Dependent on #240.
- [x] remove any hardcoded checks in any of the parsers and solely depend on the the required attributes defined via `format.py` in all of the parsers. Dependent on #241.
- [x] Include required attributes from `format.py` in the current odML validation. Dependent on #242.
- [x] Add validation for single Sections and Properties in `validation.py`. Dependent on #243.
- [x] Make all attributes in `section.py` and `property.py` optional, but run the single Section/Property validation within the `init` to make sure all required attributes have been provided and are correct. Dependent on #244.
- [x] Run the validation for both XML parser and Dict parser on load and save.

**Comment by mpsonntag** [comment]
All points have been addressed in previous PRs.
