### ISSUE TITLE
RDF subclassing feature

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/python-odml#397]
The current implementation of the `odml.tools.RDFWriter` includes an export of Sections with specific Section.types as RDF classes different than odml:Section. In detail, if a `Section.type` is found in the type mapping in file `odml.resources.section_subclasses.yaml`, then the mapped entry is used as new RDF class name instead of `odml:Section`. As an example, a section with type `cell` would be exported as `odml:Cell`.

The idea is to specify Sections of interest which are easier to find in a SPARQL query, if they are proper RDF subclasses of class `odml:Section`. A query that would look like `SELECT * WHERE {?s type odml:Section and ?s odml:hasType 'cell' .}` could be simplified to `SELECT * WHERE {?s type odml:Cell .}` but would still also be found when searching for the more generic `SELECT * WHERE {?s type odml:Section .}` since `odml:Cell` is an RDF subclass of `odml:Section`.

The current implementation does not include an export of everything required to enable this kind of RDF class inference.

The following list of issues map the road to full compliance to RDF class inference in the RDFWriter
- [x] The RDFWriter should make RDF subclassing an OPTIONAL feature. See issue #394.
- [x] Allow custom Section.type to RDF Subclass name mapping. See issue #395.
- [x] Create proper RDF subclasses. See issue #396.

**Comment by mpsonntag** [comment]
Closed via #400.
